name: Website Deployment
on:
  push:
    # Only deploy upon new commits to `main`
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6

      - run: npm install
      - name: Build website with VIKE
        run: npm run build
        env:
          PUBLIC_ENV__API_URL: ${{ vars.API_URL }}
          PUBLIC_ENV__API_TOKEN: ${{ vars.API_TOKEN }}
          PUBLIC_ENV__TYPESENSE_API_KEY: ${{ vars.TYPESENSE_API_KEY }}
          PUBLIC_ENV__TYPESENSE_API_URL: ${{ vars.TYPESENSE_API_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages
          folder: dist/client
          # Remove previous build files
          clean: true
          # Remove history — avoiding exploding Git repository size
          single-commit: true
          # Do not remove the `.nojekyll` file: we have manually added an empty `.nojekyll` file at the root of the `gh-pages` branch and we don't want having to re-create it after each build.
          clean-exclude: |
            .nojekyll
permissions:
  contents: write